apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/env: playground
      # app.kubernetes.io/name: argocd # This is not needed as it is already set in the base.
      app.kubernetes.io/owner: cloud-platform
      app.kubernetes.io/group: system
      app.kubernetes.io/managed-by: argocd
    includeTemplates: true
namespace: argocd
helmCharts:
  - name: argo-cd
    repo: https://argoproj.github.io/argo-helm
    releaseName: argocd
    version: 7.7.16
    valuesFile: ./values-argocd.yaml
    namespace: argocd
    includeCRDs: true
  - name: argocd-apps
    repo: https://argoproj.github.io/argo-helm
    releaseName: argocd-apps
    version: 2.0.0
    valuesFile: ./values-argocd-apps.yaml
    namespace: argocd
    includeCRDs: true
resources:
  - ../base
