apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  project: bare-metal-kubernetes-playground
  destination:
    namespace: metallb
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:GotoRen/bare-metal-kubernetes-playground.git
    path: k8s/manifests/platform/metallb/playground
    targetRevision: main
  syncPolicy:
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
    automated:
      selfHeal: true
      prune: true
  ignoreDifferences: ## see: https://github.com/metallb/metallb/issues/1681
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: addresspools.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
