apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/env: playground
    includeTemplates: true
helmCharts:
  - name: metallb
    repo: https://charts.bitnami.com/bitnami
    releaseName: metallb
    version: 6.3.15
    includeCRDs: true
    namespace: metallb
    valuesFile: ./values.yaml
resources:
  - ../base
  - ./l2-config.yaml
