apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: prometheus-pushgateway
      app.kubernetes.io/env: playground
      app.kubernetes.io/owner: cloud-platform
      app.kubernetes.io/group: monitoring
      app.kubernetes.io/managed-by: argocd
    includeTemplates: true
namespace: monitoring
helmCharts:
  - name: prometheus-pushgateway
    repo: https://prometheus-community.github.io/helm-charts
    releaseName: prometheus-pushgateway
    version: 2.17.0
    valuesFile: ./values.yaml
    namespace: monitoring
    includeCRDs: true
