apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
  namespace: argocd
spec:
  project: bare-metal-kubernetes-playground
  destination:
    namespace: kube-prometheus-stack
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:GotoRen/bare-metal-kubernetes-playground.git
    path: k8s/manifests/platform/kube-prometheus-stack/playground
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true # metadata.annotations: Too long: must have at most 262144 bytes を回避する
    automated:
      selfHeal: true
      prune: true
