apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/env: playground
      # app.kubernetes.io/name: kube-prometheus-stack # This is not needed as it is already set in the base.
      app.kubernetes.io/owner: cloud-platform
      app.kubernetes.io/group: monitoring
      # app.kubernetes.io/managed-by: argocd # This is not needed as it is already set in the base.
    includeTemplates: true
namespace: monitoring
helmCharts:
  - name: kube-prometheus-stack
    repo: https://prometheus-community.github.io/helm-charts
    version: 68.3.0
    releaseName: kube-prometheus-stack
    valuesFile: ./values.yaml
    namespace: monitoring
    includeCRDs: true
resources:
  - ../base
