apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-service-monitors
  namespace: argocd
spec:
  project: bare-metal-kubernetes-playground
  destination:
    namespace: prometheus-service-monitors
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:GotoRen/bare-metal-kubernetes-playground.git
    path: k8s/manifests/platform/prometheus-service-monitors/playground
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
