apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pushgateway
  labels:
    prometheus: agent
spec:
  selector:
    matchLabels:
      enablePushgatewayMetrics: "true"
  namespaceSelector:
    any: true
  endpoints:
    - port: http
      path: /metrics
      interval: 20s
