apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/env: playground
    includeTemplates: true
helmCharts:
  - name: flannel
    repo: https://flannel-io.github.io/flannel
    releaseName: flannel
    version: v0.26.3
    includeCRDs: true
    namespace: flannel
    valuesFile: ./values.yaml
resources:
  - ../base
