apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx
  namespace: nginx
spec:
  project: bare-metal-kubernetes-playground
  destination:
    namespace: nginx
    server: https://kubernetes.default.svc
  source:
    repoURL: git@github.com:GotoRen/bare-metal-kubernetes-playground.git
    path: k8s/manifests/services/nginx/playground
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
