apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
labels:
  - pairs:
      app.kubernetes.io/name: nginx
      app.kubernetes.io/env: playground
      app.kubernetes.io/owner: backend
      app.kubernetes.io/group: undefined
    includeTemplates: true
namespace: nginx
resources:
  - ./deployment.yaml
  - ./namespace.yaml
  - ./service.yaml
