apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
  namespace: nginx
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.68.230 # assigning IPv4 addresses for `Service` resources
  selector:
    app: nginx-pod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
